server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.h2.console.enabled=false
spring.thymeleaf.cache=true
server.error.include-message=never
businesshub.integration.webhook-api-key=${BUSINESSHUB_INTEGRATION_WEBHOOK_API_KEY}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
