spring.application.name=integration-dashboard

spring.datasource.url=jdbc:h2:mem:integrationhub;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username=sa
spring.datasource.password=
server.port=${PORT:8080}
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false

server.error.include-message=always

management.endpoints.web.exposure.include=health,info

businesshub.email.enabled=false
businesshub.email.from=noreply@businesshub.local
businesshub.email.ops-inbox=ops@businesshub.local

businesshub.security.admin.username=admin
businesshub.security.admin.password=Admin@123
businesshub.security.admin.role=ADMIN
businesshub.security.ops.username=ops
businesshub.security.ops.password=Ops@123
businesshub.security.ops.role=OPS
